<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>thebeaverretriever</AssemblyName>
    <RootNamespace>Calloatti.TheBeaverRetriever</RootNamespace>
  </PropertyGroup>

  <Import Project="CommonModSettings.props" />
  
  <ItemGroup>
    <Publicize Include="Timberborn.Wandering" />
  </ItemGroup>

</Project>
